name: Build and Release

# Se activa al hacer push del tag
on:
  push:
    tags:
      - 'v*'

# Permiso de escritura
permissions:
  contents: write

jobs:
  build:
    name: Build on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - uses: actions/checkout@v4

    # Configuramos Python
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    # Instalaci√≥n de dependencias
    - name: Install dependencies
      run: |
        # Actualiza pip
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install pyinstaller

    # Construye el binario
    - name: Build with PyInstaller
      run: |
        python -m PyInstaller PyClassicGames.spec

    # Renombrado para Linux
    - name: Rename Binary (Linux)
      if: matrix.os == 'ubuntu-latest'
      run: mv dist/PyClassicGames dist/PyClassicGames-Linux-${{ github.ref_name }}

    # Renombrado para Windows
    - name: Rename Binary (Windows)
      if: matrix.os == 'windows-latest'
      run: mv dist/PyClassicGames.exe dist/PyClassicGames-Windows-${{ github.ref_name }}.exe

    # Sube el archivo a una ruta temporal
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: binary-${{ matrix.os }}
        path: dist/PyClassicGames*

  release:
    # Crea el Release
    name: Create Release
    needs: build
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    # Extrae el mensaje del tag anotado y lo guarda en una variable de entorno
    - name: Extract Tag Message
      id: tag_message
      run: |
        TAG_MSG=$(git tag -l --format='%(contents)' ${{ github.ref_name }})
        echo "RELEASE_BODY<<EOF" >> $GITHUB_ENV
        echo "$TAG_MSG" >> $GITHUB_ENV
        echo "EOF" >> $GITHUB_ENV

    # Descarga los archivos de antes
    - name: Download Artifacts
      uses: actions/download-artifact@v4
      with:
        pattern: binary-*
        merge-multiple: true
        path: dist

    # Publica el borrador del Release
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        draft: true
        generate_release_notes: true
        body: ${{ env.RELEASE_BODY }}
        files: dist/*